### PR TITLE
Fix for new version of clusterGenes

### PR DESCRIPTION
**Pull request by ifiddes**
Fix for issue #213.

### CODE REVIEW

**Review by diekhans — COMMENTED** [review]
looks good to me.

**Comment by estolle** [comment]
Thanks for this quick fix,

In the file /cat/filter_transmap.py there is still the deprecated argument "minOverlappingBases" which needs to be replaced with "ignoreBases" (lines 151, 154). I did this manually and it runs further now =)

I, however have another error because the CAT/augustus_cfgs/extrinsic.ETM1.cfg is not found. I have CAT installed in a different folder. Is there a way to tell CAT where to find this file so that I do not run the projects inside the CAT folder?

**Comment by ifiddes** [comment]
Pushed a fix, thanks for catching that. I also added documentation on the flags that will allow you to run CAT from another directory. You will need to point CAT explicitly to each augustus config file you plan to use using the 4 flags.

**Comment by estolle** [comment]
Great. thank you so much. this worked and the pipeline completed without errors on the test data set. Now the real data can start =)

**Pull request merged**
